(******************************************************************************)
(*                                                                            *)
(*                        CODE OF HAMMURABI (c. 1754 BCE)                     *)
(*                                                                            *)
(*     Formalizing the 282 laws of Hammurabi: lex talionis, property          *)
(*     rights, family law, commercial transactions, and judicial              *)
(*     procedures of ancient Babylon.                                         *)
(*                                                                            *)
(*     "Anu and Bel called by name me, Hammurabi, the exalted prince,         *)
(*      to bring about the rule of righteousness in the land."                *)
(*     - Prologue, Code of Hammurabi                                          *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 6, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
